# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postitboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='priority',
            field=models.CharField(choices=[('N', 'Normal'), ('U', 'Urgent'), ('C', 'Critical')], max_length=1),
        ),
        migrations.AlterField(
            model_name='message',
            name='readcheck',
            field=models.BooleanField(default=False),
        ),
    ]
