# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postitboard', '0002_auto_20171012_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='groupname',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
